---
# tasks file for sample-mysql
- name: Create primary partition on sdb
  parted:
    device: /dev/sdb
    part_end: 800MB
    number: 1
    state: present

- name: Install lvm packages
  yum:
    state: present
    name: lvm*

- name: Create logical volume group
  lvg:
    state: present
    vg: vg_database
    pvs: /dev/sdb1

- name: Create logical volume
  lvol:
    state: present
    lv: lv_mysql
    vg: vg_database
    size: 512

- name: Create XFS filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql 

- name: Mount lvm permanently
  mount:
    path: /mnt/mysql_backups
    state: mounted
    src: /dev/vg_database/lv_mysql 
    fstype: xfs

- name: Install mysql package
  yum:
    name: mysql-community-server,MySQL-python
    state: present

- name: Allow all incoming traffic on 3306/tcp
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled

- name: Change root password
  mysql_user:
    name: root
    login_password: ''
    password: "{{ database_password }}"

- name: Copy .my.cnf to root for future use
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf

- name: Copy configuration template
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mysql

- name: Create patito user 
  mysql_user:
    name: patito 
    password: 1234
    priv: '*.*:ALL'
    state: present
#    login_unix_socket: /var/lib/mysql/mysql.sock
 
- name: Start and enable MySQL service
  service:
    name: mysqld
    state: started
    enabled: yes
