- hosts: database
  become: yes
  tasks:
  - name: Create custom fact directory
    file:
      state: directory
      path: /etc/ansible/facts.d

  - name: Create custom fact
    copy:
      content: '"mysql"' 
      dest: /etc/ansible/facts.d/custom.sample_exam.server_role.fact
  
  - setup:

  - debug: var=ansible_local
