- hosts: proxy
  become: yes
  gather_facts: no
  tasks:
  - name: Create cron job for root
    cron:
      special_time: hourly
      user: root
      job: "date >> /var/log/time.log"
      state: present
      name: time logging job
