- hosts: database
  become: yes
  gather_facts: no
  tasks:
  - name: Add yum repo
    yum_repository:
      state: present
      name: mysql56-community
      description: "MySQL 5.6 YUM Repo"
      baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/
      gpgcheck: yes
      gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
      enabled: true
