- hosts: database 
  become: yes
  gather_facts: false
  tasks:
  - name: Copy template
    template:
      src: server_list.j2
      dest: /etc/server_list.txt
      owner: automation
      mode: 0600
      setype: net_conf_t
