- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Set banner to /etc/motd
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: Banner
      line: "Banner /etc/motd"
      state: present
    notify: restart sshd

  - name: Disable X11Forwarding
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "X11Forwarding"
      line: "X11Forwarding no"
      state: present 
    notify: restart sshd

  - name: Set MaxAuthTries to 3
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: MaxAuthTries
      line: MaxAuthTries 3
      state: present
    notify: restart sshd

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted
