- hosts: all
  become: true
  gather_facts: yes
  tasks:
  - debug: var=ansible_memfree_mb

  - name: Set swappiness
    sysctl:
      name: vm.swappiness
      value: 10
      state: present
    when: ansible_memfree_mb > 14  
  
  - debug: var=vm.swappiness

  - fail:
      msg: Server memory less than 14MB
    when: ansible_memfree_mb < 14
